### ISSUE TITLE
Not getting refresh token

### ISSUE THREAD

**Issue by sivamamidi-REISys** [mdpauley/ti.mp5systems.salesforce#1]
Not populating refresh token if we use responsetype = token from server.

**Comment by mdpauley** [comment]
Can you provide the error

**Comment by sivamamidi-REISys** [comment]
Thank you for quick response. I think it's not purely configuration issue at salesforce connected app oauth settings.

**Comment by mdpauley** [comment]
@sivamamidi-REISys Are you with REI Systems in Northern Virginia? I'm located in Vienna if you need any help with this.
